//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNet.Fluent.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdoNet.Fluent.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrução já tem parâmetros para execução.
        /// </summary>
        internal static string AlreadyParameterized {
            get {
                return ResourceManager.GetString("AlreadyParameterized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de &quot;{0}&quot; não foram encontrados.
        /// </summary>
        internal static string ConnectionNotFound {
            get {
                return ResourceManager.GetString("ConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumento \&quot;{0}\&quot; já cadastrado.
        /// </summary>
        internal static string DuplicateArgument {
            get {
                return ResourceManager.GetString("DuplicateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não efetuada por tentativa de cadastrar chave existente.
        /// </summary>
        internal static string DuplicateKeyError {
            get {
                return ResourceManager.GetString("DuplicateKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não efetuada por violar relacionamento entre informações.
        /// </summary>
        internal static string ForeignKeyError {
            get {
                return ResourceManager.GetString("ForeignKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão não está configurada para executar várias consultas.
        /// </summary>
        internal static string MARSNotSet {
            get {
                return ResourceManager.GetString("MARSNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; não está configurado para processamento assíncrono.
        /// </summary>
        internal static string NoAsync {
            get {
                return ResourceManager.GetString("NoAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi definido comando para executar.
        /// </summary>
        internal static string NoCommand {
            get {
                return ResourceManager.GetString("NoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram definidos parâmetros de execução.
        /// </summary>
        internal static string NoParameters {
            get {
                return ResourceManager.GetString("NoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableDirect não suportado.
        /// </summary>
        internal static string NoTableDirect {
            get {
                return ResourceManager.GetString("NoTableDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precisão deve ser igual ou maior que zero.
        /// </summary>
        internal static string PrecisionOutOfRange {
            get {
                return ResourceManager.GetString("PrecisionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação já cadastrada.
        /// </summary>
        internal static string PrimaryKeyError {
            get {
                return ResourceManager.GetString("PrimaryKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provedor não encontrado.
        /// </summary>
        internal static string ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provedor &quot;{0}&quot; não suportado.
        /// </summary>
        internal static string ProviderNotSupported {
            get {
                return ResourceManager.GetString("ProviderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrução já tem parâmetros para execução.
        /// </summary>
        internal static string ReturnParameterFirst {
            get {
                return ResourceManager.GetString("ReturnParameterFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala deve ser igual ou maior que zero.
        /// </summary>
        internal static string ScaleOutOfRange {
            get {
                return ResourceManager.GetString("ScaleOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho deve ser maior que zero.
        /// </summary>
        internal static string SizeOutOfRange {
            get {
                return ResourceManager.GetString("SizeOutOfRange", resourceCulture);
            }
        }
    }
}
